In [7]:
import pandas as pd

In [5]:
df = pd.read_excel('Jamu_metabolite_.xlsx')

In [6]:
print(df.shape)
df.head(3)

(397, 3493)


V1  C1  C2  C3  C4  C5  C6  C7  C8  C9  ...  C3483  C3484  C3485  \
0  J00050   0   0   0   0   0   0   0   0   0  ...      0      0      0   
1  J00113   0   0   0   0   0   0   0   0   0  ...      0      0      0   
2  J00258   0   0   0   0   0   0   0   0   0  ...      0      0      0   

   C3486  C3487  C3488  C3489  C3490  baru  label update  
0      0      0      0      0      0     1             6  
1      0      0      0      0      0     1             6  
2      0      0      0      0      0     1             6  

[3 rows x 3493 columns]

In [80]:
df["label update"].value_counts()

3    170
4     82
6     66
2     58
1     19
Name: label update, dtype: int64

In [76]:
# remove colomn with all values are zero
df = df.loc[:, (df != 0).any(axis=0)]
# remove data with label 5
df.drop(df[df["label update"] == 5].index, inplace=True)

In [77]:
del df['V1']
del df['baru']

In [78]:
x = df.iloc[:,0:2255]
y = df.iloc[:,2255:]

In [14]:
# Filtering formula metabolite

In [15]:
X_train = x 
X_test = x
y_train = y
y_test = y

In [43]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing

In [44]:
classifier = svm.SVC(kernel='rbf')
classifier.fit(X_train, y_train)

C:\Users\Lab PC\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVC()

In [45]:
predictions = classifier.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
y_score = classifier.decision_function(X_test)

0.8784810126582279
[[  4   0  15   0   0]
 [  0  48   6   2   2]
 [  0   0 169   1   0]
 [  0   1   8  73   0]
 [  0   1   5   7  53]]


In [48]:
temp = df
temp['temp'] = 0
temp['prediction']= predictions
list = []

In [52]:
print(temp.shape)
temp.head(3)

(395, 2258)


C1  C2  C4  C5  C6  C7  C8  C9  C10  C11  ...  C3483  C3484  C3486  C3487  \
0   0   0   0   0   0   0   0   0    0    0  ...      0      0      0      0   
1   0   0   0   0   0   0   0   0    0    0  ...      0      0      0      0   
2   0   0   0   0   0   0   0   0    0    0  ...      0      0      0      0   

   C3488  C3489  C3490  label update  temp  prediction  
0      0      0      0             6     0           6  
1      0      0      0             6     0           6  
2      0      0      0             6     0           6  

[3 rows x 2258 columns]

In [56]:
temp.iloc[1,2256]

0

In [57]:
for i in range(394):
    if(temp.iloc[i,2255] == temp.iloc[i,2257]):
        temp.iloc[i, 2256] = 1
    else: 
        temp.iloc[i, 2256] = 0

In [59]:
# remove data with label 2
temp.drop(temp[temp["temp"] == 0].index, inplace=True)

In [61]:
del temp['temp']
del temp['prediction']

temp.to_csv("formulaJamuMetabolite_filtered_SVM_rbf.csv")

In [62]:
# filtering linear

In [81]:
classifier = svm.SVC(kernel='linear')
classifier.fit(X_train, y_train)

C:\Users\Lab PC\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVC(kernel='linear')

In [82]:
predictions = classifier.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
y_score = classifier.decision_function(X_test)

0.9924050632911392
[[ 19   0   0   0   0]
 [  0  57   0   0   1]
 [  0   0 170   0   0]
 [  0   0   0  81   1]
 [  0   0   0   1  65]]


In [84]:
temp = df
temp['temp'] = 0
temp['prediction']= predictions
list = []

In [85]:
for i in range(394):
    if(temp.iloc[i,2255] == temp.iloc[i,2257]):
        temp.iloc[i, 2256] = 1
    else: 
        temp.iloc[i, 2256] = 0

In [88]:
# remove data with label 2
temp.drop(temp[temp["temp"] == 0].index, inplace=True)

In [90]:
del temp['temp']
del temp['prediction']

temp.to_csv("formulaJamuMetabolite_filtered_SVM_Linear.csv")

In [2]:
data_filtered_svm_rbf = pd.read_csv("formulaJamuMetabolite_filtered_SVM_rbf.csv")
print(data_viltered_svm_rbf.shape)

(346, 2257)


In [3]:
data_filtered_svm_linear = pd.read_csv("formulaJamuMetabolite_filtered_SVM_Linear.csv")
print(data_filtered_svm_linear.shape)

(391, 2257)
