In [53]:
import pandas as pd
import numpy as np

In [54]:
df = pd.read_csv("dataUnaniSebelumPre-proses.csv.csv")
print(df.head())
print(df.shape)

FileNotFoundError: [Errno 2] File b'dataUnaniSebelumPre-proses.csv.csv' does not exist: b'dataUnaniSebelumPre-proses.csv.csv'

In [55]:
df

0    1    2    3    4    5    6    7    8  \
0              Anqaruya Kabir  F01  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1          Etrifal Ustukhudus  F04  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2              Etrifal Gudadi  F07  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3              Etrifal saghir  F08  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4              Etrifal Deedan  F09  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
5               Etrifal Muqil  F12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
6              Etrifal Mundee  F13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
7            Khamira Abresham  F18  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
8    Khamira Abresham Arshadi  F19  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
9          Kkamira Khashkhash  F20  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
10          Khamira Zahrmohra  F27  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
11           Jowarish Anarain  F29  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12        Jowarish Wood Tursh  F31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
13       Jowarish Wood Shireen F32  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
14             Jowarish Kamuni F33  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
15       Jowarish Kamuni Kabir F34  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
16     Jowarish Kamuni Mus-hil F35  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
17             Jowarish Kundur F36  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
18             Jowarish Qurtum F37  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
19          Jowarish Tabasheer F41  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
20           Jowarish Falafili F43  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
21            Jowarish Bisbasa F44  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
22            Jowarish Mustagi F45  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
23            Jowarish Zarooni F46  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
24          Jowarish Zanjabeel F47  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
25            Jowarish Zarishk F48  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
26        Jowarish Shahreyaran F50  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
27                Tiryaq Arbaa F51  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
28         Dawaul Kurkum Kabir F55  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
29                   Dayaqooza F59  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
..                             ...  ...  ...  ...  ...  ...  ...  ...  ...   
345             Sufoof Himzin F574  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
346            Sufoof Humuzin F575  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
347            Surma Akseerin F578  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
348            Kuhlul-Jawaher F579  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
349              Surma Chikni F580  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
350               Surma Sadaf F581  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
351            Burood Kafoori F582  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
352              Surma Beenai F583  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
353       Surma Muqavvi Basar F584  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
354            Surma Rowshnai F585  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
355      Aabe-e-Namak Shireen F588  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
356              Ubtan Jamali F589  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
357           Khezab La-jawab F590  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
358             Gargara Lahat F591  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
359              Gasool Besan F592  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
360         Gaza Bahar-e Husn F593  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
361          Gaza Husn-e Afza F594  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
362             Nafookh Sarai F595  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
363             Farzaja Qabiz F596  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
364              Bukhoor Dama F597  0.0  0.0  0.0  0.0 

In [56]:
X = df.iloc[:,1:4688]
y = df.iloc[:,4688]

In [57]:
X_train = X
X_test = X
y_train = y
y_test = y

In [58]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing

In [59]:
# Create a simple classifier

classifier = svm.SVC(gamma= 'auto')
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [60]:
predictions = classifier.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
y_score = classifier.decision_function(X_test)

0.26666666666666666
[[  0   0  13   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   3   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0 100   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  14   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  10   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  22   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   3   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  19   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  26   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  19   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  22   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   6   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  31   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  40   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  31   0   0   0   0   0   0   0 

In [61]:

# Create a simple classifier

classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [62]:
predictions = classifier.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

0.808
[[ 8  0  4  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  1  2  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 98  0  0  0  0  0  0  1  0  0  0  1  0  0]
 [ 0  0  4 10  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  7  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  2  0  0 20  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0]
 [ 1  0  4  0  0  0  0 13  0  0  0  0  0  0  0  1]
 [ 0  0  5  0  0  0  0  0 21  0  0  0  0  0  0  0]
 [ 0  0  3  1  0  0  0  0  0 15  0  0  0  0  0  0]
 [ 0  0  6  0  0  0  0  0  0  0 16  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  5  0  0  0  0]
 [ 0  0  7  0  0  1  0  0  0  0  0  0 22  0  0  1]
 [ 0  0  7  1  1  0  0  1  0  0  0  0  0 29  0  1]
 [ 0  0  7  0  0  0  0  1  0  0  0  0  0  1 22  0]
 [ 0  0  1  0  0  0  1  0  0  0  0  0  0  1  0 13]]


In [63]:
df[4689]= predictions

In [64]:
df

0    1    2    3    4    5    6    7    8  \
0              Anqaruya Kabir  F01  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1          Etrifal Ustukhudus  F04  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2              Etrifal Gudadi  F07  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3              Etrifal saghir  F08  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4              Etrifal Deedan  F09  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
5               Etrifal Muqil  F12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
6              Etrifal Mundee  F13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
7            Khamira Abresham  F18  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
8    Khamira Abresham Arshadi  F19  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
9          Kkamira Khashkhash  F20  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
10          Khamira Zahrmohra  F27  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
11           Jowarish Anarain  F29  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12        Jowarish Wood Tursh  F31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
13       Jowarish Wood Shireen F32  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
14             Jowarish Kamuni F33  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
15       Jowarish Kamuni Kabir F34  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
16     Jowarish Kamuni Mus-hil F35  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
17             Jowarish Kundur F36  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
18             Jowarish Qurtum F37  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
19          Jowarish Tabasheer F41  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
20           Jowarish Falafili F43  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
21            Jowarish Bisbasa F44  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
22            Jowarish Mustagi F45  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
23            Jowarish Zarooni F46  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
24          Jowarish Zanjabeel F47  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
25            Jowarish Zarishk F48  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
26        Jowarish Shahreyaran F50  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
27                Tiryaq Arbaa F51  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
28         Dawaul Kurkum Kabir F55  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
29                   Dayaqooza F59  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
..                             ...  ...  ...  ...  ...  ...  ...  ...  ...   
345             Sufoof Himzin F574  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
346            Sufoof Humuzin F575  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
347            Surma Akseerin F578  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
348            Kuhlul-Jawaher F579  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
349              Surma Chikni F580  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
350               Surma Sadaf F581  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
351            Burood Kafoori F582  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
352              Surma Beenai F583  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
353       Surma Muqavvi Basar F584  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
354            Surma Rowshnai F585  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
355      Aabe-e-Namak Shireen F588  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
356              Ubtan Jamali F589  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
357           Khezab La-jawab F590  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
358             Gargara Lahat F591  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
359              Gasool Besan F592  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
360         Gaza Bahar-e Husn F593  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
361          Gaza Husn-e Afza F594  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
362             Nafookh Sarai F595  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
363             Farzaja Qabiz F596  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
364              Bukhoor Dama F597  0.0  0.0  0.0  0.0 

In [65]:
list = []

In [66]:
df[4690]= 0

In [67]:
for i in range(374):
    if(df.iloc[i,4688] == df.iloc[i,4689]):
        df.iloc[i, 4690] = 1
    else: 
        df.iloc[i, 4690] = 0


In [68]:
df

0    1    2    3    4    5    6    7    8  \
0              Anqaruya Kabir  F01  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1          Etrifal Ustukhudus  F04  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2              Etrifal Gudadi  F07  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3              Etrifal saghir  F08  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4              Etrifal Deedan  F09  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
5               Etrifal Muqil  F12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
6              Etrifal Mundee  F13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
7            Khamira Abresham  F18  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
8    Khamira Abresham Arshadi  F19  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
9          Kkamira Khashkhash  F20  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
10          Khamira Zahrmohra  F27  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
11           Jowarish Anarain  F29  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12        Jowarish Wood Tursh  F31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
13       Jowarish Wood Shireen F32  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
14             Jowarish Kamuni F33  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
15       Jowarish Kamuni Kabir F34  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
16     Jowarish Kamuni Mus-hil F35  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
17             Jowarish Kundur F36  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
18             Jowarish Qurtum F37  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
19          Jowarish Tabasheer F41  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
20           Jowarish Falafili F43  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
21            Jowarish Bisbasa F44  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
22            Jowarish Mustagi F45  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
23            Jowarish Zarooni F46  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
24          Jowarish Zanjabeel F47  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
25            Jowarish Zarishk F48  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
26        Jowarish Shahreyaran F50  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
27                Tiryaq Arbaa F51  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
28         Dawaul Kurkum Kabir F55  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
29                   Dayaqooza F59  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
..                             ...  ...  ...  ...  ...  ...  ...  ...  ...   
345             Sufoof Himzin F574  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
346            Sufoof Humuzin F575  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
347            Surma Akseerin F578  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
348            Kuhlul-Jawaher F579  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
349              Surma Chikni F580  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
350               Surma Sadaf F581  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
351            Burood Kafoori F582  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
352              Surma Beenai F583  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
353       Surma Muqavvi Basar F584  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
354            Surma Rowshnai F585  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
355      Aabe-e-Namak Shireen F588  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
356              Ubtan Jamali F589  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
357           Khezab La-jawab F590  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
358             Gargara Lahat F591  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
359              Gasool Besan F592  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
360         Gaza Bahar-e Husn F593  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
361          Gaza Husn-e Afza F594  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
362             Nafookh Sarai F595  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
363             Farzaja Qabiz F596  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
364              Bukhoor Dama F597  0.0  0.0  0.0  0.0 

In [69]:
a = df[df[4690] == 1]

In [70]:
a['4688'].value_counts()

3     98
16    29
17    22
15    22
10    21
6     19
13    16
11    15
18    13
8     13
4     10
1      8
5      7
14     5
7      3
2      1
Name: 4688, dtype: int64