In [2]:
import pandas as pd
import numpy as np

In [3]:
# data formula Jamu after filtering SVM rbf
data = pd.read_csv("formulaJamuMetabolite_filtered_SVM_rbf.csv")
del data['Unnamed: 0']

In [4]:
print(data.shape)
data.head()

(346, 2256)


C1  C2  C4  C5  C6  C7  C8  C9  C10  C11  ...  C3480  C3482  C3483  C3484  \
0   0   0   0   0   0   0   0   0    0    0  ...      0      0      0      0   
1   0   0   0   0   0   0   0   0    0    0  ...      0      0      0      0   
2   0   0   0   0   0   0   0   0    0    0  ...      0      0      0      0   
3   0   0   0   0   0   0   0   0    0    0  ...      0      0      0      0   
4   0   0   0   0   0   0   0   0    0    0  ...      0      0      0      0   

   C3486  C3487  C3488  C3489  C3490  label update  
0      0      0      0      0      0             6  
1      0      0      0      0      0             6  
2      0      0      0      0      0             6  
3      0      0      0      0      0             6  
4      0      0      0      0      0             6  

[5 rows x 2256 columns]

In [196]:
df = data
df.head()

C1  C2  C4  C5  C6  C7  C8  C9  C10  C11  ...  C3480  C3482  C3483  C3484  \
0   0   0   0   0   0   0   0   0    0    0  ...      0      0      0      0   
1   0   0   0   0   0   0   0   0    0    0  ...      0      0      0      0   
2   0   0   0   0   0   0   0   0    0    0  ...      0      0      0      0   
3   0   0   0   0   0   0   0   0    0    0  ...      0      0      0      0   
4   0   0   0   0   0   0   0   0    0    0  ...      0      0      0      0   

   C3486  C3487  C3488  C3489  C3490  label update  
0      0      0      0      0      0             6  
1      0      0      0      0      0             6  
2      0      0      0      0      0             6  
3      0      0      0      0      0             6  
4      0      0      0      0      0             6  

[5 rows x 2256 columns]

In [197]:
# # remove data with label 1
# df.drop(df[df["label update"] == 1].index, inplace=True)

In [198]:
df['label update'].value_counts()

3    169
4     72
6     53
2     48
1      4
Name: label update, dtype: int64

In [199]:
x = df.iloc[:, :2255]
y = df.iloc[:, 2255:]

# Traning menggunakan Random Forest

In [202]:
# Load libraries
import pandas as pd
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing

In [203]:
from sklearn import model_selection

validation_size = 0.25
seed = 7
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(x, y, test_size=validation_size, random_state=seed)


## RF default

In [204]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, Y_train)
y_pred = rf.predict(X_test)

In [205]:
from sklearn.metrics import roc_curve, auc
print(accuracy_score(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))

0.8735632183908046
[[ 0  0  0  0  1]
 [ 0  9  1  1  0]
 [ 0  1 47  0  0]
 [ 0  2  2 13  1]
 [ 0  1  0  1  7]]


In [206]:
# searching important metabolite

In [207]:
from keras.wrappers.scikit_learn import KerasClassifier, KerasRegressor
import eli5
from eli5.sklearn import PermutationImportance

In [208]:
perm = PermutationImportance(rf).fit(x, y)
feature_importance_model = eli5.show_weights(perm)

In [209]:
explanation = eli5.formatters.as_dataframe.explain_weights_df(perm,feature_names = x.columns.tolist(),)

In [211]:
explanation.to_excel('featureImportance_rf_formulaJamu_filteredSVMrbf_nonSmote.xlsx')

In [212]:
VI = pd.read_excel('featureImportance_rf_formulaJamu_filteredSVMrbf_nonSmote.xlsx')
del VI['Unnamed: 0']

In [217]:
df['label update'].value_counts()

3    169
4     72
6     53
2     48
1      4
Name: label update, dtype: int64

In [221]:
for i in range(1,7):
    VI[i] = 0

In [223]:
for i in range(len(VI)):
    uniq = df['label update'][df[(VI['feature'].iloc[i])] == 1].unique()
    print(uniq)
    for j in uniq:
        j = str(j)
        if (len(j.split(',')) == 1):
            if (int(j) !=0):
                VI[int(j)].iloc[i] = 1

[6 4 3 2]
[6 4 3 2]
[3 4]
[6 4 2 3]
[6 4 3 2]
[6 4 3]
[6 4 1 3 2]
[3 4]
[3 4]
[6 4 3]
[4 3 2]
[6 4 3 2]
[3]
[4 3 6 2]
[4 3 6 2]
[3]
[3]
[6 3]
[2]
[3]
[6 4 3 2]
[4 3 6]
[2]
[1 4 3 6 2]
[6 4 2 3]
[3 6]
[3 6]
[6 3 4]
[1 4 3 6 2]
[6 4 2]
[6]
[6 4 2 3]
[2]
[6 4 2 3]
[6 4 3 2]
[6 4 2 3]
[3 6 2]
[6]
[3]
[3]
[6 4 3 2]
[3 2]
[3 2]
[4 6]
[6 4 2]
[6 4 1 3 2]
[6 4 1 3 2]
[4]
[4]
[4]
[4]
[4]
[3 6 2 4]
[3]
[4 1 3 6 2]
[4]
[6 3 4]
[6 3]
[3]
[6 3 4]
[6 4 2 3]
[4 3 6 2]
[6 3 4]
[2]
[2 3]
[3]
[3]
[3]
[6 4 3 2]
[4 2 3 6]
[6 4 3 2]
[3]
[4 3 2]
[4 3 2]
[6 3 2]
[6 4 3 2]
[2 3]
[2 3]
[6 4 2 3]
[2]
[6 4 2 3]
[]
[6 3 2]
[6 3 2]
[3]
[6]
[6 4 3 2]
[4 3 2]
[4 3 6 2]
[3 4]
[6 4 3 2]
[4]
[1 6 2]
[2]
[6]
[6 4 3 2]
[4 6]
[4 6]
[4 6]
[3]
[2]
[4 3 2]
[4 3 2]
[4 3 6 2]
[3]
[6]
[3 4]
[3]
[4 3 6 2]
[3]
[6]
[6 1 4 3]
[6 4]
[3]
[6 4 3 2]
[4 3 2]
[3]
[6 3]
[6 3]
[2 3]
[4 3 6 2]
[6 4 3 2]
[4 3 6 2]
[6 4 2 3]
[6 3]
[4 3 2]
[4 3 6 2]
[3]
[4]
[6 4 3 2]
[6]
[3]
[3]
[3]
[6 4 3 2]
[3]
[6 4 3 2]
[4 3 2]
[3]
[2]
[1 4 3 2]
[6 4 3 2]
[

[6 4 1 3 2]
[3]
[6 2]
[6 1 4 3]
[1 4 3 6 2]
[6 3]
[6]
[3]
[6 2]
[6 2]
[3]
[6 2]
[6 2]
[6 2]
[4 2 3 6]
[4 3 6 2]
[3]
[6 1 4 3]
[6 1 4 3]
[6 1 4 3]
[6 1 4 3]
[6 1 4 3]
[6 1 4 3]
[6 1 4 3]
[6 1 4 3]
[6 4 3 2]
[3 4]
[4 3 6 2]
[]
[1 6 2]
[1 6 2]
[1 6 2]
[4 3 6 2]
[1 6 2]
[3 6]
[4 2 3 6]
[6 4 3 2]
[3 2]
[3]
[3 6]
[3]
[4 3 6 2]
[6 4 3 2]
[3]
[3 6]
[4]
[6]
[6 4 2]
[3]
[]
[4 3 6]
[6]
[3]
[3]
[4 2 3 6]
[6 3]
[6 4 2 3]
[1 4 3 6 2]
[4 2]
[4 2]
[6 3]
[6 3]
[6 4 3 2]
[3 2 4]
[3 6 4]
[6 4 3]
[3]
[2]
[4]
[6 4 3 2]
[4 3 2]
[6 4 3 2]
[6 4]
[4 3 6 2]
[3 6]
[3 6]
[3 6]
[3 6]
[6 2 4]
[6 4 1 2 3]
[6 4 3 2]
[4 6]
[6 2]
[6 4 2 1 3]
[3 6]
[6]
[3]
[6]
[3 6]
[3 6]
[3 6]
[3 6]
[3 6]
[3 6]
[3 6]
[2]
[2]
[2]
[2]
[2]
[2]
[6 4 3]
[6]
[6 4 2]
[6]
[4 3 6 2]
[4 3 6 2]
[4 3 6 2]
[3 4]
[6 4 1 3 2]
[6 4 3 2]
[6 2]
[4 3 2]
[3]
[6]
[3]
[6 1 4 3]
[4 3 2]
[6 4 2 3]
[6 4 3 2]
[6 4 3 2]
[4 2 3 6]
[4]
[6]
[6]
[6 4 1 3 2]
[6]
[6 4 3 2]
[4]
[3]
[4 3 6 2]
[4]
[6 4 3 2]
[6 4 3 2]
[4]
[2]
[3 6]
[2 3]
[4 3 6 2]
[6 4 2 3]
[2]
[6]
[3]
[6

In [225]:
VI.to_excel('HasilMetaboliteImportant_filteredSVM_RBV_NonSMOTE.xlsx')

In [111]:
from sklearn.model_selection import RandomizedSearchCV

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt'], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 4], 'bootstrap': [True, False]}


In [112]:
from sklearn.ensemble import RandomForestRegressor
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestRegressor()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)

# Fit the random search model
rf_random.fit(X_train, Y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:    4.3s
[Parallel(n_jobs=-1)]: Done 130 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  4.2min finished


RandomizedSearchCV(cv=3, estimator=RandomForestRegressor(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=42, verbose=2)

In [113]:
rf_random.best_params_

{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 110,
 'bootstrap': True}

In [95]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 1000,min_samples_split =2, min_samples_leaf = 1, max_features ='sqrt', max_depth =20, bootstrap=True)
rf.fit(X_train, Y_train) 
y_pred = rf.predict(X_test)

In [96]:
from sklearn.metrics import roc_curve, auc
print(accuracy_score(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))

0.810126582278481
[[ 3  0  1  0  0]
 [ 0  5  0  1  2]
 [ 0  1 34  1  0]
 [ 0  0  3 14  2]
 [ 0  0  2  2  8]]


# Traning Menggunakan SVM

In [97]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing

In [98]:
# Create a simple classifier
classifier = svm.SVC()
classifier.fit(X_train, Y_train)

SVC()

In [99]:
predictions = classifier.predict(X_test)
print(accuracy_score(Y_test, predictions))
print(confusion_matrix(Y_test, predictions))
y_score = classifier.decision_function(X_test)

0.759493670886076
[[ 0  0  4  0  0]
 [ 0  6  1  1  0]
 [ 0  0 33  3  0]
 [ 0  0  5 14  0]
 [ 0  1  3  1  7]]


## Tuning Parameter SVM

In [100]:
import numpy as np
import pandas as pd

def warn(*args, **kwargs): pass
import warnings
warnings.warn = warn

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, log_loss

from sklearn.svm import SVC
from sklearn import decomposition

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [101]:
train = array[:,0:2255]
test = array[:,2255]

In [102]:
# Set the parameters by cross-validation
tuned_parameters = [{'kernel': ['rbf'], 'gamma': [1e-2, 1e-3, 1e-4, 1e-5],
                     'C': [0.001, 0.10, 0.1, 10, 25, 50, 100, 1000]},
                    {'kernel': ['sigmoid'], 'gamma': [1e-2, 1e-3, 1e-4, 1e-5],
                     'C': [0.001, 0.10, 0.1, 10, 25, 50, 100, 1000]},
                    {'kernel': ['linear'], 'C': [0.001, 0.10, 0.1, 10, 25, 50, 100, 1000]}
                   ]

scores = ['precision', 'recall']

for score in scores:
    print("# Tuning hyper-parameters for %s" % score)
    print()

    clf = GridSearchCV(SVC(C=1), tuned_parameters, cv=5,
                       scoring='%s_macro' % score)
    clf.fit(X_train, Y_train)

    print("Best parameters set found on development set:")
    print()
    print(clf.best_params_)
    print()
    print("Grid scores on development set:")
    print()
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, clf.cv_results_['params']):
        print("%0.3f (+/-%0.03f) for %r"
              % (mean, std * 2, params))
    print()

# print("Detailed classification report:")
# print()
# print("The model is trained on the full development set.")
# print("The scores are computed on the full evaluation set.")
# print()
# y_true, y_pred = y_test, clf.predict(X_test)
# print(classification_report(y_true, y_pred))
# print()

# Tuning hyper-parameters for precision

Best parameters set found on development set:

{'C': 50, 'gamma': 0.001, 'kernel': 'rbf'}

Grid scores on development set:

0.086 (+/-0.002) for {'C': 0.001, 'gamma': 0.01, 'kernel': 'rbf'}
0.086 (+/-0.002) for {'C': 0.001, 'gamma': 0.001, 'kernel': 'rbf'}
0.086 (+/-0.002) for {'C': 0.001, 'gamma': 0.0001, 'kernel': 'rbf'}
0.086 (+/-0.002) for {'C': 0.001, 'gamma': 1e-05, 'kernel': 'rbf'}
0.086 (+/-0.002) for {'C': 0.1, 'gamma': 0.01, 'kernel': 'rbf'}
0.086 (+/-0.002) for {'C': 0.1, 'gamma': 0.001, 'kernel': 'rbf'}
0.086 (+/-0.002) for {'C': 0.1, 'gamma': 0.0001, 'kernel': 'rbf'}
0.086 (+/-0.002) for {'C': 0.1, 'gamma': 1e-05, 'kernel': 'rbf'}
0.086 (+/-0.002) for {'C': 0.1, 'gamma': 0.01, 'kernel': 'rbf'}
0.086 (+/-0.002) for {'C': 0.1, 'gamma': 0.001, 'kernel': 'rbf'}
0.086 (+/-0.002) for {'C': 0.1, 'gamma': 0.0001, 'kernel': 'rbf'}
0.086 (+/-0.002) for {'C': 0.1, 'gamma': 1e-05, 'kernel': 'rbf'}
0.679 (+/-0.111) for {'C': 10, 'gamma': 0.01, '

In [104]:
clf.best_params_

{'C': 1000, 'gamma': 0.001, 'kernel': 'sigmoid'}

In [105]:
# Create a simple classifier

classifier = svm.SVC(gamma= 0.001, C= 1000, kernel='sigmoid')
classifier.fit(X_train, Y_train)

SVC(C=1000, gamma=0.001, kernel='sigmoid')

In [106]:
predictions = classifier.predict(X_test)
print(accuracy_score(Y_test, predictions))
print(confusion_matrix(Y_test, predictions))
y_score = classifier.decision_function(X_test)

0.7848101265822784
[[ 4  0  0  0  0]
 [ 0  5  0  1  2]
 [ 1  2 32  1  0]
 [ 0  0  3 15  1]
 [ 0  2  2  2  6]]


# Traning dengan deep learning

In [107]:
from keras.utils.np_utils import to_categorical
y = to_categorical(y)

In [108]:
y[1:5]

array([[0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [109]:
from sklearn import model_selection

validation_size = 0.2
seed = 7
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(x, y, test_size=validation_size, random_state=seed)


In [110]:
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from tensorflow import keras
from keras.models import Sequential
#from keras.optimizers import SGD, RMSprop, Adam
from keras.layers import Dense, Activation, Dropout
from sklearn.model_selection import StratifiedKFold

In [111]:
model = Sequential()
model.add(Dense(input_dim=X_train.shape[1], units=463,kernel_initializer='normal', bias_initializer='zeros'))
model.add(Activation('relu'))
for i in range(0, 6):
    model.add(Dense(units=463, kernel_initializer='normal',bias_initializer='zeros'))
    model.add(Activation('relu'))
    model.add(Dropout(.4))

model.add(Dense(units = 7))
model.add(Activation('softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, Y_train,batch_size=24,epochs=100,verbose=1,validation_data=(X_test, Y_test))
score = model.evaluate(X_test, Y_test, verbose=1)

Epoch 1/100
13/13 [==============================] - 1s 15ms/step - loss: 0.4519 - accuracy: 0.3173 - val_loss: 0.3779 - val_accuracy: 0.4557
Epoch 2/100
13/13 [==============================] - 0s 11ms/step - loss: 0.3518 - accuracy: 0.3878 - val_loss: 0.3335 - val_accuracy: 0.4557
Epoch 3/100
13/13 [==============================] - 0s 10ms/step - loss: 0.3091 - accuracy: 0.4455 - val_loss: 0.2867 - val_accuracy: 0.6456
Epoch 4/100
13/13 [==============================] - 0s 10ms/step - loss: 0.2655 - accuracy: 0.5449 - val_loss: 0.2398 - val_accuracy: 0.6203
Epoch 5/100
13/13 [==============================] - 0s 11ms/step - loss: 0.2270 - accuracy: 0.6122 - val_loss: 0.2144 - val_accuracy: 0.6709
Epoch 6/100
13/13 [==============================] - 0s 9ms/step - loss: 0.1911 - accuracy: 0.7147 - val_loss: 0.2102 - val_accuracy: 0.6962
Epoch 7/100
13/13 [==============================] - 0s 9ms/step - loss: 0.1666 - accuracy: 0.7179 - val_loss: 0.1978 - val_accuracy: 0.6962
Epoch 8/

In [112]:
score

[0.8615517020225525, 0.7721518874168396]

In [113]:
model.history

In [78]:
# import pandas as pd
# import numpy as np
# import lazypredict
# from lazypredict.Supervised import LazyClassifier
# from sklearn.model_selection import train_test_split

In [2]:
# data formula Jamu after filtering SVM rbf
data = pd.read_csv("formulaJamuMetabolite_filtered_SVM_rbf.csv")
del data['Unnamed: 0']

In [4]:
data.head(2)

C1  C2  C4  C5  C6  C7  C8  C9  C10  C11  ...  C3480  C3482  C3483  C3484  \
0   0   0   0   0   0   0   0   0    0    0  ...      0      0      0      0   
1   0   0   0   0   0   0   0   0    0    0  ...      0      0      0      0   

   C3486  C3487  C3488  C3489  C3490  label update  
0      0      0      0      0      0             6  
1      0      0      0      0      0             6  

[2 rows x 2256 columns]

In [6]:
df = data
array = df.values
x = array[:,0:2255]
y = array[:,2255]
y = y.astype('int')

In [9]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization

In [10]:
# Melakukan proses standarisasi
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(x)

In [11]:
# split the dataset into the training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [12]:
# build the lightgbm model
import lightgbm as lgb
clf = lgb.LGBMClassifier()
clf.fit(X_train, y_train)

LGBMClassifier()

In [13]:
# predict the results
y_pred=clf.predict(X_test)

In [14]:
y_pred_train = clf.predict(X_train)

In [15]:
# print the scores on training and test set

print('Training set score: {:.4f}'.format(clf.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(clf.score(X_test, y_test)))

Training set score: 1.0000
Test set score: 0.8654


In [119]:
# filtering svm RBF tanpa oversampling
df = data
array = df.values
x = array[:,0:2255]
y = array[:,2255]
y = y.astype('int')

In [120]:
# Melakukan proses standarisasi
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x = sc.fit_transform(x)

x = pd.DataFrame(x)
y = pd.DataFrame(y)

In [ ]:
{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 110,
 'bootstrap': True}

In [128]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.3)

In [129]:
temp_model = []
akurasi = []
recall = []
precision = []

In [130]:
# random forest test set
from sklearn.model_selection import RepeatedStratifiedKFold
seed = 7
kf = RepeatedStratifiedKFold(n_splits=10, random_state=seed, n_repeats=1)
val_acc_cv = []
j = 0
for train_index, test_index in kf.split(x,y):
    j+=1
    print(f"Fold {j} :")
    X_train,X_test = x.iloc[train_index],x.iloc[test_index]
    y_train,y_test = y.iloc[train_index],y.iloc[test_index]
    
    # Instantiate model
    #Create a Gaussian Classifier
    model = RandomForestClassifier(n_estimators=1000, n_jobs=-1, max_features="sqrt", max_depth=110, bootstrap=True, min_samples_split=2, min_samples_leaf=1)
    model.fit(X_train, y_train)
    
    temp_model.append(model)
    #Import scikit-learn metrics module for accuracy calculation
    val_acc_cv.append(round(model.score(X_test, y_test), 4)*100)
    print('Accuracy:',round(model.score(X_test, y_test), 4)*100, '%')
    
    predict = model.predict(X_test)
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import recall_score
    from sklearn.metrics import precision_score
    acc_score = accuracy_score(y_test,predict)
    recall_score = recall_score(y_test,predict, average = 'weighted')
    precision_score = precision_score(y_test,predict, average = 'weighted')
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test, predict)
    print(cm)
    print("Akurasi")
    print(acc_score)
    print("Recall")
    print(recall_score)
    print("Precision") 
    print(precision_score)
    print("")
    akurasi.append(acc_score)
    recall.append(recall_score)
    precision.append(precision_score)

Fold 1 :
Accuracy: 80.0 %
[[ 4  1  0  0]
 [ 0 16  1  0]
 [ 0  1  6  0]
 [ 1  1  2  2]]
Akurasi
0.8
Recall
0.8
Precision
0.8280701754385965

Fold 2 :
Accuracy: 77.14 %
[[ 4  0  0  1]
 [ 0 15  2  0]
 [ 1  1  5  0]
 [ 0  1  2  3]]
Akurasi
0.7714285714285715
Recall
0.7714285714285715
Precision
0.7825396825396825

Fold 3 :
Accuracy: 91.43 %
[[ 5  0  0  0]
 [ 0 17  0  0]
 [ 1  1  5  0]
 [ 0  1  0  5]]
Akurasi
0.9142857142857143
Recall
0.9142857142857143
Precision
0.9250626566416039

Fold 4 :
Accuracy: 85.71 %
[[ 5  0  0  0]
 [ 1 16  0  0]
 [ 1  0  6  1]
 [ 0  0  2  3]]
Akurasi
0.8571428571428571
Recall
0.8571428571428571
Precision
0.866326530612245

Fold 5 :
Accuracy: 80.0 %
[[ 3  2  0  0]
 [ 1 16  0  0]
 [ 0  0  5  3]
 [ 0  0  1  4]]
Akurasi
0.8
Recall
0.8
Precision
0.8109977324263039

Fold 6 :
Accuracy: 71.43 %
[[ 0  0  1  0  0]
 [ 0  4  0  1  0]
 [ 0  4 13  0  0]
 [ 0  0  2  4  1]
 [ 0  0  1  0  4]]
Akurasi
0.7142857142857143
Recall
0.7142857142857143
Precision
0.7171428571428572

Fold 7 

In [131]:
summary_result = pd.DataFrame()
summary_result['Accuracy_Best_Parameter'] = akurasi
summary_result['Recall_Best_Parameter'] = recall
summary_result['Precision_Best_Parameter'] = precision

In [132]:
summary_result.describe()

Accuracy_Best_Parameter  Recall_Best_Parameter  \
count                    10.00                  10.00   
mean                      0.82                   0.82   
std                       0.06                   0.06   
min                       0.71                   0.71   
25%                       0.80                   0.80   
50%                       0.81                   0.81   
75%                       0.86                   0.86   
max                       0.91                   0.91   

       Precision_Best_Parameter  
count                     10.00  
mean                       0.83  
std                        0.06  
min                        0.72  
25%                        0.80  
50%                        0.83  
75%                        0.86  
max                        0.93

In [29]:
# cara oversampling menggunakan SMOTE
import pandas as pd
import matplotlib.pyplot as plt

from imblearn.over_sampling import SMOTE
import eli5
import numpy as np
import pandas as pd
from eli5.sklearn import PermutationImportance
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
from keras.wrappers.scikit_learn import KerasClassifier, KerasRegressor

In [30]:
seed = 123
k = 3
sm = SMOTE(sampling_strategy='auto', k_neighbors=k, random_state=seed)
X_res, y_res = sm.fit_resample(x, y)
x = X_res
y = y_res
x = pd.DataFrame(x)
y = pd.DataFrame(y)

In [33]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2)

In [35]:
temp_model = []
akurasi = []
recall = []
precision = []

In [36]:
# random forest test set
from sklearn.model_selection import RepeatedStratifiedKFold
seed = 7
kf = RepeatedStratifiedKFold(n_splits=10, random_state=seed, n_repeats=1)
val_acc_cv = []
j = 0
for train_index, test_index in kf.split(x,y):
    j+=1
    print(f"Fold {j} :")
    X_train,X_test = x.iloc[train_index],x.iloc[test_index]
    y_train,y_test = y.iloc[train_index],y.iloc[test_index]
    
    # Instantiate model
    #Create a Gaussian Classifier
    model = RandomForestClassifier(n_estimators=2000, n_jobs=-1, max_features="sqrt", max_depth=100, bootstrap=True, min_samples_split=5, min_samples_leaf=1)
    model.fit(X_train, y_train)
    
    temp_model.append(model)
    #Import scikit-learn metrics module for accuracy calculation
    val_acc_cv.append(round(model.score(X_test, y_test), 4)*100)
    print('Accuracy:',round(model.score(X_test, y_test), 4)*100, '%')
    
    predict = model.predict(X_test)
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import recall_score
    from sklearn.metrics import precision_score
    acc_score = accuracy_score(y_test,predict)
    recall_score = recall_score(y_test,predict, average = 'weighted')
    precision_score = precision_score(y_test,predict, average = 'weighted')
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test, predict)
    print(cm)
    print("Akurasi")
    print(acc_score)
    print("Recall")
    print(recall_score)
    print("Precision") 
    print(precision_score)
    print("")
    akurasi.append(acc_score)
    recall.append(recall_score)
    precision.append(precision_score)

Fold 1 :
Accuracy: 82.35 %
[[17  0  0  0  0]
 [ 0 16  0  0  1]
 [ 0  0 17  0  0]
 [ 1  3  1  9  3]
 [ 3  0  1  2 11]]
Akurasi
0.8235294117647058
Recall
0.8235294117647058
Precision
0.8195762132604237

Fold 2 :
Accuracy: 91.75999999999999 %
[[17  0  0  0  0]
 [ 0 16  0  1  0]
 [ 0  0 16  1  0]
 [ 1  0  0 16  0]
 [ 1  0  1  2 13]]
Akurasi
0.9176470588235294
Recall
0.9176470588235294
Precision
0.9271826625386997

Fold 3 :
Accuracy: 92.94 %
[[17  0  0  0  0]
 [ 1 15  0  0  1]
 [ 0  1 16  0  0]
 [ 0  0  0 16  1]
 [ 0  1  0  1 15]]
Akurasi
0.9294117647058824
Recall
0.9294117647058824
Precision
0.9300653594771242

Fold 4 :
Accuracy: 92.94 %
[[16  0  1  0  0]
 [ 1 16  0  0  0]
 [ 0  0 15  2  0]
 [ 0  0  0 16  1]
 [ 1  0  0  0 16]]
Akurasi
0.9294117647058824
Recall
0.9294117647058824
Precision
0.9312908496732026

Fold 5 :
Accuracy: 95.28999999999999 %
[[17  0  0  0  0]
 [ 0 17  0  0  0]
 [ 0  0 17  0  0]
 [ 0  1  0 16  0]
 [ 2  1  0  0 14]]
Akurasi
0.9529411764705882
Recall
0.9529411764705882
P

In [37]:
summary_result = pd.DataFrame()
summary_result['Accuracy_Best_Parameter'] = akurasi
summary_result['Recall_Best_Parameter'] = recall
summary_result['Precision_Best_Parameter'] = precision

In [38]:
summary_result

Accuracy_Best_Parameter  Recall_Best_Parameter  Precision_Best_Parameter
0                     0.82                   0.82                      0.82
1                     0.92                   0.92                      0.93
2                     0.93                   0.93                      0.93
3                     0.93                   0.93                      0.93
4                     0.95                   0.95                      0.96
5                     0.89                   0.89                      0.90
6                     0.90                   0.90                      0.91
7                     0.88                   0.88                      0.88
8                     0.85                   0.85                      0.85
9                     0.94                   0.94                      0.94

In [80]:
(82+92+93+93+95+89+90+99+85+94)/ 10

91.2

In [58]:
# data sebelum over sampling
# data formula Jamu after filtering SVM rbf
data = pd.read_csv("formulaJamuMetabolite_filtered_SVM_Linear.csv")
del data['Unnamed: 0']

In [59]:
array = data.values
x = array[:,0:2255]
y = array[:,2255]
y = y.astype('int')

In [60]:
x = pd.DataFrame(x)
y = pd.DataFrame(y)

In [61]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2)

In [62]:
temp_model = []
akurasi = []
recall = []
precision = []

In [63]:
# random forest test set
from sklearn.model_selection import RepeatedStratifiedKFold
seed = 7
kf = RepeatedStratifiedKFold(n_splits=10, random_state=seed, n_repeats=1)
val_acc_cv = []
j = 0
for train_index, test_index in kf.split(x,y):
    j+=1
    print(f"Fold {j} :")
    X_train,X_test = x.iloc[train_index],x.iloc[test_index]
    y_train,y_test = y.iloc[train_index],y.iloc[test_index]
    
    # Instantiate model
    #Create a Gaussian Classifier
    model = RandomForestClassifier(n_estimators=2000, n_jobs=-1, max_features="sqrt", max_depth=100, bootstrap=True, min_samples_split=5, min_samples_leaf=1)
    model.fit(X_train, y_train)
    
    temp_model.append(model)
    #Import scikit-learn metrics module for accuracy calculation
    val_acc_cv.append(round(model.score(X_test, y_test), 4)*100)
    print('Accuracy:',round(model.score(X_test, y_test), 4)*100, '%')
    
    predict = model.predict(X_test)
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import recall_score
    from sklearn.metrics import precision_score
    acc_score = accuracy_score(y_test,predict)
    recall_score = recall_score(y_test,predict, average = 'weighted')
    precision_score = precision_score(y_test,predict, average = 'weighted')
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test, predict)
    print(cm)
    print("Akurasi")
    print(acc_score)
    print("Recall")
    print(recall_score)
    print("Precision") 
    print(precision_score)
    print("")
    akurasi.append(acc_score)
    recall.append(recall_score)
    precision.append(precision_score)

Fold 1 :
Accuracy: 65.0 %
[[ 2  0  0  0  0]
 [ 0  2  1  1  2]
 [ 0  0 15  1  1]
 [ 0  1  2  3  2]
 [ 0  0  1  2  4]]
Akurasi
0.65
Recall
0.65
Precision
0.649018379281537

Fold 2 :
Accuracy: 79.49000000000001 %
[[ 0  0  2  0  0]
 [ 0  5  0  0  0]
 [ 0  1 15  1  0]
 [ 0  1  0  6  1]
 [ 0  1  1  0  5]]
Akurasi
0.7948717948717948
Recall
0.7948717948717948
Precision
0.7687728937728939

Fold 3 :
Accuracy: 82.05 %
[[ 1  0  1  0  0]
 [ 0  4  0  1  0]
 [ 0  0 17  0  0]
 [ 0  0  0  6  2]
 [ 0  0  1  2  4]]
Akurasi
0.8205128205128205
Recall
0.8205128205128205
Precision
0.8259109311740891

Fold 4 :
Accuracy: 71.78999999999999 %
[[ 1  0  0  1  0]
 [ 0  4  0  1  0]
 [ 0  2 13  2  0]
 [ 0  1  2  4  1]
 [ 0  0  0  1  6]]
Akurasi
0.717948717948718
Recall
0.717948717948718
Precision
0.7473341473341473

Fold 5 :
Accuracy: 76.92 %
[[ 1  0  0  0  0]
 [ 0  2  2  0  2]
 [ 0  1 16  0  0]
 [ 0  1  1  5  1]
 [ 0  0  0  1  6]]
Akurasi
0.7692307692307693
Recall
0.7692307692307693
Precision
0.7602339181286549

Fol

In [64]:
summary_result = pd.DataFrame()
summary_result['Accuracy_Best_Parameter'] = akurasi
summary_result['Recall_Best_Parameter'] = recall
summary_result['Precision_Best_Parameter'] = precision

In [65]:
summary_result

Accuracy_Best_Parameter  Recall_Best_Parameter  Precision_Best_Parameter
0                     0.65                   0.65                      0.65
1                     0.79                   0.79                      0.77
2                     0.82                   0.82                      0.83
3                     0.72                   0.72                      0.75
4                     0.77                   0.77                      0.76
5                     0.74                   0.74                      0.75
6                     0.79                   0.79                      0.80
7                     0.82                   0.82                      0.78
8                     0.74                   0.74                      0.74
9                     0.67                   0.67                      0.69

In [57]:
# setelah oversampling

In [66]:
seed = 123
k = 3
sm = SMOTE(sampling_strategy='auto', k_neighbors=k, random_state=seed)
X_res, y_res = sm.fit_resample(x, y)
x = X_res
y = y_res
x = pd.DataFrame(x)
y = pd.DataFrame(y)

In [67]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2)

In [74]:
temp_model = []
akurasi = []
recall = []
precision = []

In [75]:
# random forest test set
from sklearn.model_selection import RepeatedStratifiedKFold
seed = 7
kf = RepeatedStratifiedKFold(n_splits=10, random_state=seed, n_repeats=1)
val_acc_cv = []
j = 0
for train_index, test_index in kf.split(x,y):
    j+=1
    print(f"Fold {j} :")
    X_train,X_test = x.iloc[train_index],x.iloc[test_index]
    y_train,y_test = y.iloc[train_index],y.iloc[test_index]
    
    # Instantiate model
    #Create a Gaussian Classifier
    model = RandomForestClassifier(n_estimators=2000, n_jobs=-1, max_features="sqrt", max_depth=100, bootstrap=True, min_samples_split=5, min_samples_leaf=1)
    model.fit(X_train, y_train)
    
    temp_model.append(model)
    #Import scikit-learn metrics module for accuracy calculation
    val_acc_cv.append(round(model.score(X_test, y_test), 4)*100)
    print('Accuracy:',round(model.score(X_test, y_test), 4)*100, '%')
    
    predict = model.predict(X_test)
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import recall_score
    from sklearn.metrics import precision_score
    acc_score = accuracy_score(y_test,predict)
    recall_score = recall_score(y_test,predict, average = 'weighted')
    precision_score = precision_score(y_test,predict, average = 'weighted')
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test, predict)
    print(cm)
    print("Akurasi")
    print(acc_score)
    print("Recall")
    print(recall_score)
    print("Precision") 
    print(precision_score)
    print("")
    akurasi.append(acc_score)
    recall.append(recall_score)
    precision.append(precision_score)

Fold 1 :
Accuracy: 84.71 %
[[16  0  1  0  0]
 [ 2 10  0  3  2]
 [ 0  0 17  0  0]
 [ 0  1  0 15  1]
 [ 0  0  1  2 14]]
Akurasi
0.8470588235294118
Recall
0.8470588235294118
Precision
0.8532492103699534

Fold 2 :
Accuracy: 82.35 %
[[17  0  0  0  0]
 [ 0 15  0  1  1]
 [ 0  1 13  2  1]
 [ 1  1  0 14  1]
 [ 2  0  3  1 11]]
Akurasi
0.8235294117647058
Recall
0.8235294117647058
Precision
0.8216690009337068

Fold 3 :
Accuracy: 81.17999999999999 %
[[16  0  1  0  0]
 [ 3 14  0  0  0]
 [ 2  0 12  3  0]
 [ 2  2  0 12  1]
 [ 1  0  1  0 15]]
Akurasi
0.8117647058823529
Recall
0.8117647058823529
Precision
0.8272619047619048

Fold 4 :
Accuracy: 81.17999999999999 %
[[17  0  0  0  0]
 [ 1 16  0  0  0]
 [ 2  3 11  1  0]
 [ 1  1  0 14  1]
 [ 1  0  0  5 11]]
Akurasi
0.8117647058823529
Recall
0.8117647058823529
Precision
0.8378787878787879

Fold 5 :
Accuracy: 84.71 %
[[16  0  0  0  1]
 [ 2 12  0  2  1]
 [ 0  0 17  0  0]
 [ 0  2  1 13  1]
 [ 1  0  0  2 14]]
Akurasi
0.8470588235294118
Recall
0.8470588235294118
P

In [76]:
summary_result = pd.DataFrame()
summary_result['Accuracy_Best_Parameter'] = akurasi
summary_result['Recall_Best_Parameter'] = recall
summary_result['Precision_Best_Parameter'] = precision

summary_result

Accuracy_Best_Parameter  Recall_Best_Parameter  Precision_Best_Parameter
0                     0.85                   0.85                      0.85
1                     0.82                   0.82                      0.82
2                     0.81                   0.81                      0.83
3                     0.81                   0.81                      0.84
4                     0.85                   0.85                      0.85
5                     0.89                   0.89                      0.90
6                     0.80                   0.80                      0.80
7                     0.82                   0.82                      0.83
8                     0.86                   0.86                      0.86
9                     0.79                   0.79                      0.79

In [77]:
summary_result.describe()

Accuracy_Best_Parameter  Recall_Best_Parameter  \
count                    10.00                  10.00   
mean                      0.83                   0.83   
std                       0.03                   0.03   
min                       0.79                   0.79   
25%                       0.81                   0.81   
50%                       0.82                   0.82   
75%                       0.85                   0.85   
max                       0.89                   0.89   

       Precision_Best_Parameter  
count                     10.00  
mean                       0.84  
std                        0.03  
min                        0.79  
25%                        0.82  
50%                        0.83  
75%                        0.85  
max                        0.90